name: dartamaker
description: A command-line Dart script and library that generates JSON or CSV data in bulk.
version: 2.0.0
homepage: https://github.com/shamblett/dartamaker

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 args: '^2.0.0'

executables:
 dartamaker: dartamaker

dev_dependencies:
 test: '^1.16.8'
 pedantic: '^1.11.0'
 mockito: '^5.0.2'


