name: dartamaker
description: A command-line Dart script and library that generates JSON or CSV data in bulk.
version: 1.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/dartamaker

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 args: '^1.5.2'

executables:
 dartamaker: dartamaker

dev_dependencies:
 test: '^1.3.0'
 coverage: '^0.12.4'
 dart_dev: '^2.1.0'
 dart_style: '^1.1.3'
 mockito: '^3.0.0'

