name: dartamaker
description: A command-line Dart script and library that generates JSON or CSV data in bulk.
version: 1.0.3
homepage: https://github.com/shamblett/dartamaker

environment:
 sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
 args: '^1.6.0'

executables:
 dartamaker: dartamaker

dev_dependencies:
 test: '^1.14.2'
 pana: '^0.13.6'
 pedantic: '^1.9.0'
 mockito: '^4.1.3'


