name: dartamaker
description: A command-line Dart script and library that generates JSON or CSV data in bulk.
version: 3.0.2
homepage: https://github.com/shamblett/dartamaker

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.7.0 <4.0.0'

dependencies:
 args: '^2.7.0'
 characters: '^1.4.0'

executables:
 dartamaker: dartamaker

dev_dependencies:
 test: '^1.26.0'
 mockito: '^5.4.6'
 lints: '^5.1.1'
 dart_code_metrics_presets: '^2.22.0'


